//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace FODLApi.FODLWebServiceMinesite {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FODL_Web_Service_Binding", Namespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service")]
    public partial class FODL_Web_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DownloadDepartmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadToNavisionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateShortcutDimCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback AssignNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDocumentNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback NewBatchNameOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FODL_Web_Service() {
            this.Url = global::FODLApi.Properties.Settings.Default.FODLApi_FODLWebServiceMinesite_FODL_Web_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DownloadDepartmentCompletedEventHandler DownloadDepartmentCompleted;
        
        /// <remarks/>
        public event UploadToNavisionCompletedEventHandler UploadToNavisionCompleted;
        
        /// <remarks/>
        public event ValidateShortcutDimCodeCompletedEventHandler ValidateShortcutDimCodeCompleted;
        
        /// <remarks/>
        public event AssignNoCompletedEventHandler AssignNoCompleted;
        
        /// <remarks/>
        public event GetDocumentNoCompletedEventHandler GetDocumentNoCompleted;
        
        /// <remarks/>
        public event NewBatchNameCompletedEventHandler NewBatchNameCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service:DownloadDepartment", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", ResponseElementName="DownloadDepartment_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string DownloadDepartment() {
            object[] results = this.Invoke("DownloadDepartment", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DownloadDepartmentAsync() {
            this.DownloadDepartmentAsync(null);
        }
        
        /// <remarks/>
        public void DownloadDepartmentAsync(object userState) {
            if ((this.DownloadDepartmentOperationCompleted == null)) {
                this.DownloadDepartmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDownloadDepartmentOperationCompleted);
            }
            this.InvokeAsync("DownloadDepartment", new object[0], this.DownloadDepartmentOperationCompleted, userState);
        }
        
        private void OnDownloadDepartmentOperationCompleted(object arg) {
            if ((this.DownloadDepartmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DownloadDepartmentCompleted(this, new DownloadDepartmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service:UploadToNavision", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", ResponseElementName="UploadToNavision_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string UploadToNavision(string batchNo, int lineNo, string itemNo, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime postingDate, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime documentDate, int qtyRequest, string equipmentNo, string officeCode, string fuelCode, string locationCode, string deptCode, string documentNo) {
            object[] results = this.Invoke("UploadToNavision", new object[] {
                        batchNo,
                        lineNo,
                        itemNo,
                        postingDate,
                        documentDate,
                        qtyRequest,
                        equipmentNo,
                        officeCode,
                        fuelCode,
                        locationCode,
                        deptCode,
                        documentNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UploadToNavisionAsync(string batchNo, int lineNo, string itemNo, System.DateTime postingDate, System.DateTime documentDate, int qtyRequest, string equipmentNo, string officeCode, string fuelCode, string locationCode, string deptCode, string documentNo) {
            this.UploadToNavisionAsync(batchNo, lineNo, itemNo, postingDate, documentDate, qtyRequest, equipmentNo, officeCode, fuelCode, locationCode, deptCode, documentNo, null);
        }
        
        /// <remarks/>
        public void UploadToNavisionAsync(string batchNo, int lineNo, string itemNo, System.DateTime postingDate, System.DateTime documentDate, int qtyRequest, string equipmentNo, string officeCode, string fuelCode, string locationCode, string deptCode, string documentNo, object userState) {
            if ((this.UploadToNavisionOperationCompleted == null)) {
                this.UploadToNavisionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadToNavisionOperationCompleted);
            }
            this.InvokeAsync("UploadToNavision", new object[] {
                        batchNo,
                        lineNo,
                        itemNo,
                        postingDate,
                        documentDate,
                        qtyRequest,
                        equipmentNo,
                        officeCode,
                        fuelCode,
                        locationCode,
                        deptCode,
                        documentNo}, this.UploadToNavisionOperationCompleted, userState);
        }
        
        private void OnUploadToNavisionOperationCompleted(object arg) {
            if ((this.UploadToNavisionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadToNavisionCompleted(this, new UploadToNavisionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service:ValidateShortcutDimCode", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", ResponseElementName="ValidateShortcutDimCode_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ValidateShortcutDimCode(int fieldNumber, ref string shortcutDimCode) {
            object[] results = this.Invoke("ValidateShortcutDimCode", new object[] {
                        fieldNumber,
                        shortcutDimCode});
            shortcutDimCode = ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateShortcutDimCodeAsync(int fieldNumber, string shortcutDimCode) {
            this.ValidateShortcutDimCodeAsync(fieldNumber, shortcutDimCode, null);
        }
        
        /// <remarks/>
        public void ValidateShortcutDimCodeAsync(int fieldNumber, string shortcutDimCode, object userState) {
            if ((this.ValidateShortcutDimCodeOperationCompleted == null)) {
                this.ValidateShortcutDimCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateShortcutDimCodeOperationCompleted);
            }
            this.InvokeAsync("ValidateShortcutDimCode", new object[] {
                        fieldNumber,
                        shortcutDimCode}, this.ValidateShortcutDimCodeOperationCompleted, userState);
        }
        
        private void OnValidateShortcutDimCodeOperationCompleted(object arg) {
            if ((this.ValidateShortcutDimCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateShortcutDimCodeCompleted(this, new ValidateShortcutDimCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service:AssignNo", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", ResponseElementName="AssignNo_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string AssignNo(string vNoSeries) {
            object[] results = this.Invoke("AssignNo", new object[] {
                        vNoSeries});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AssignNoAsync(string vNoSeries) {
            this.AssignNoAsync(vNoSeries, null);
        }
        
        /// <remarks/>
        public void AssignNoAsync(string vNoSeries, object userState) {
            if ((this.AssignNoOperationCompleted == null)) {
                this.AssignNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAssignNoOperationCompleted);
            }
            this.InvokeAsync("AssignNo", new object[] {
                        vNoSeries}, this.AssignNoOperationCompleted, userState);
        }
        
        private void OnAssignNoOperationCompleted(object arg) {
            if ((this.AssignNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AssignNoCompleted(this, new AssignNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service:GetDocumentNo", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", ResponseElementName="GetDocumentNo_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetDocumentNo(string batchNo) {
            object[] results = this.Invoke("GetDocumentNo", new object[] {
                        batchNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDocumentNoAsync(string batchNo) {
            this.GetDocumentNoAsync(batchNo, null);
        }
        
        /// <remarks/>
        public void GetDocumentNoAsync(string batchNo, object userState) {
            if ((this.GetDocumentNoOperationCompleted == null)) {
                this.GetDocumentNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDocumentNoOperationCompleted);
            }
            this.InvokeAsync("GetDocumentNo", new object[] {
                        batchNo}, this.GetDocumentNoOperationCompleted, userState);
        }
        
        private void OnGetDocumentNoOperationCompleted(object arg) {
            if ((this.GetDocumentNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDocumentNoCompleted(this, new GetDocumentNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service:NewBatchName", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", ResponseElementName="NewBatchName_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string NewBatchName(string batchNo) {
            object[] results = this.Invoke("NewBatchName", new object[] {
                        batchNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void NewBatchNameAsync(string batchNo) {
            this.NewBatchNameAsync(batchNo, null);
        }
        
        /// <remarks/>
        public void NewBatchNameAsync(string batchNo, object userState) {
            if ((this.NewBatchNameOperationCompleted == null)) {
                this.NewBatchNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNewBatchNameOperationCompleted);
            }
            this.InvokeAsync("NewBatchName", new object[] {
                        batchNo}, this.NewBatchNameOperationCompleted, userState);
        }
        
        private void OnNewBatchNameOperationCompleted(object arg) {
            if ((this.NewBatchNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NewBatchNameCompleted(this, new NewBatchNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void DownloadDepartmentCompletedEventHandler(object sender, DownloadDepartmentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DownloadDepartmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DownloadDepartmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void UploadToNavisionCompletedEventHandler(object sender, UploadToNavisionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadToNavisionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadToNavisionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ValidateShortcutDimCodeCompletedEventHandler(object sender, ValidateShortcutDimCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateShortcutDimCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateShortcutDimCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string shortcutDimCode {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void AssignNoCompletedEventHandler(object sender, AssignNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AssignNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AssignNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetDocumentNoCompletedEventHandler(object sender, GetDocumentNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDocumentNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDocumentNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void NewBatchNameCompletedEventHandler(object sender, NewBatchNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NewBatchNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NewBatchNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591