//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FODLApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FODLEntities : DbContext
    {
        public FODLEntities()
            : base("name=FODLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Companies> Companies { get; set; }
        public virtual DbSet<Components> Components { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<Dispensers> Dispensers { get; set; }
        public virtual DbSet<Equipments> Equipments { get; set; }
        public virtual DbSet<FuelOilDetails> FuelOilDetails { get; set; }
        public virtual DbSet<FuelOils> FuelOils { get; set; }
        public virtual DbSet<FuelOilSubDetails> FuelOilSubDetails { get; set; }
        public virtual DbSet<Items> Items { get; set; }
        public virtual DbSet<Locations> Locations { get; set; }
        public virtual DbSet<Logs> Logs { get; set; }
        public virtual DbSet<LubeTrucks> LubeTrucks { get; set; }
        public virtual DbSet<NoSeries> NoSeries { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
