//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FODLApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuelOilSubDetails
    {
        public int Id { get; set; }
        public System.DateTime TimeInput { get; set; }
        public int ItemId { get; set; }
        public int ComponentId { get; set; }
        public int VolumeQty { get; set; }
        public int FuelOilDetailId { get; set; }
        public string Status { get; set; }
    
        public virtual Components Components { get; set; }
        public virtual FuelOilDetails FuelOilDetails { get; set; }
        public virtual Items Items { get; set; }
    }
}
