//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FODLApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuelOils
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FuelOils()
        {
            this.FuelOilDetails = new HashSet<FuelOilDetails>();
        }
    
        public int Id { get; set; }
        public string ReferenceNo { get; set; }
        public string Shift { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string Status { get; set; }
        public int DispenserId { get; set; }
        public int LubeTruckId { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public System.DateTime TransferDate { get; set; }
        public string TransferredBy { get; set; }
        public int OldId { get; set; }
    
        public virtual Dispensers Dispensers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FuelOilDetails> FuelOilDetails { get; set; }
        public virtual LubeTrucks LubeTrucks { get; set; }
    }
}
